name: Publish AJP to Production Server
on:
  push:
    branches:
      - production
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.AJP_FTP_SERVER }}
        ftp-username: ${{ secrets.AJP_FTP_SERVER_USERNAME }}
        ftp-password: ${{ secrets.AJP_FTP_SERVER_PASSWORD }}
